services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: |
      postgres 
      -c wal_level=logical
      -c max_replication_slots=10
      -c max_wal_senders=10
      -c wal_keep_size=1024
